recipesite/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('like/<slug:slug>', views.RecipeLike.as_view(), name='recipe_like'),
]

thymeontheroad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
    path("", include('recipesite.urls'), name='recipesite_urls'),
    path('accounts/', include('allauth.urls')),
]

recipesite/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))
CUISINE = ((0, "Italian"), (1, "Indian"), (2, "Chinese"),
           (3, "Thai"), (4, "American"), (5, "Mexican"), (6, "Middle Eastern"),
           (7, "Miscellaneous"))


class Recipe (models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipe_posts")
    created_on = models.DateTimeField(auto_now_add=True)
    ingredients = tinymce_models.HTMLField()
    method = tinymce_models.HTMLField(null=True, blank=False)
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    cuisine = models.IntegerField(choices=CUISINE, default=0)
    likes = models.ManyToManyField(
        User, related_name="recipe_likes", blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def number_of_comments(self):
        return self.comments.count()


class Comment (models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

recipesite/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

recipesite/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Recipe
from .models import Comment
from .forms import CommentForm


class RecipeList(generic.ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created_on')

        comment_deleted = False

        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
                "comment_deleted": False
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)

        commented = False
        comment_deleted = False

        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        if 'comment_id' in request.POST:
            comment_id = request.POST['comment_id']

            if 'comment_task' in request.POST:
                comment_task = request.POST['comment_task']

                if comment_task == 'edit':
                    comment_form = CommentForm(instance=Comment.objects.get(id=comment_id), data=request.POST)
                    comment = comment_form.save(commit=False)
                    comment.save()

                elif comment_task == 'delete':
                    comment = get_object_or_404(Comment, id=comment_id)
                    comment.delete()
                    comment_deleted = True

        else:
            comment_form = CommentForm(data=request.POST)

            if comment_form.is_valid():
                comment_form.instance.email = request.user.email
                comment_form.instance.name = request.user.username
                comment = comment_form.save(commit=False)
                comment.recipe = recipe
                comment.save()
                commented = True

        comments = recipe.comments.filter(approved=True).order_by('created_on')

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": commented,
                "liked": liked,
                "comment_deleted": comment_deleted,
                "comment_form": CommentForm()
            },
        )


class RecipeLike(View):

    def post(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)

        if recipe.likes.filter(id=request.user.id).exists():
            recipe.likes.remove(request.user)
        else:
            recipe.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<!-- Main site scripts/links -->

<head>
    <title>ThymeOnTheRoad Recipe Site</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Merienda&family=Oswald&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %} {% endblock %}

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation area -->

    <nav class="navbar navbar-expand-lg navbar-light light-bg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">thymeontheroad</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text">
                    Recipes from time spent travelling and cooking
                </span>
            </div>
        </div>
    </nav>

    <!-- User action messages -->

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" 
                role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"
                aria-label="Close"></button>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Main recipe content area -->

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center">Made by Tim Wright</p>
        <p class="m-0 text-center">Follow me: <a class="social fab fa-facebook-square ms-3" href="https://www.facebook.com/" target="_blank" rel="noopener"
            aria-label="Visit us on Facebook (opens in new tab)"></a>
            <a class="social fab fa-twitter-square ms-3" href="https://www.twitter.com/" target="_blank" rel="noopener"
            aria-label="Visit us on Twitter (opens in new tab)"></a>
            <a class="social fab fa-instagram-square ms-3" href="https://www.instagram.com/" target="_blank" rel="noopener"
            aria-label="Visit us on Instagram (opens in new tab)"></a>
            <a class="social fab fa-youtube-square ms-3" href="https://www.youtube.com/" target="_blank" rel="noopener"
            aria-label="Visit us on YouTube (opens in new tab)"></a></p>
    </footer>

    <!-- Timer for user action messages -->

    <script>
        setTimeout(function(){
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();

        }, 2500);

    </script>
</body>
    
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Recipe Entries Column -->

        <div class="col-12 mt-3 left">
            <div class ="row">
            {% for recipe in recipe_list %}
                <div class="col-md-4">
                    <div class="col-mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.featured_image.url %}
                                <img class="card-img-top"
                                    src="{{ recipe.featured_image.url }}" alt="{{ recipe.title }}">
                                {% else %}
                                <img class="card-img-top"
                                    src="{{ recipe.featured_image.url }}" alt="{{ recipe.title }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipe.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'recipe_detail' recipe.slug %}" class="recipe-link">
                                <h2 class="card-title">{{ recipe.title }}</h2>
                                <p class="card-text">{{ recipe.excerpt }}</p>
                            </a>
                            <div class="divider"></div>
                            <p class="card-text h6">{{ recipe.created_on }} 
                                <i class="far fa-comment"></i> {{ recipe.number_of_comments }}
                                <i class="far fa-heart"></i> {{ recipe.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}       
            {% endfor %}
            </div>
        </div>

        <!-- Pagination to load certain amount of recipes per page -->

    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{%endblock%}

templates/recipe_detail.html
{% extends 'base.html' %} {% block content %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">

                <!-- Recipe title goes in the h1 tags -->

                <h1 class="recipe-title">{{ recipe.title }}</h1>

                <!-- Recipe author goes before the | the date the recipe was created goes after -->

                <p class="recipe-subtitle"> {{ recipe.author }}| {{ recipe.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">

                <!-- The featured image URL goes in the src attribute -->

                {% if "placeholder" in recipe.featured_image.url %}
                <img src="#" alt="{{ recipe.title }}">
                {% else %}
                <img src="{{ recipe.featured_image.url }}" alt="{{ recipe.title }}">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">

                <!-- The recipe main content goes inside the card-text. -->

                <p class="card-text ">
                    {{ recipe.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'recipe_like' recipe.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="recipepost_id" value="{{ recipe.slug }}" class="btn-like"><i
                                        class="fas fa-heart"></i></button>

                                {% else %}

                                <button type="submit" name="recipepost_id" value="{{ recipe.slug }}" class="btn-like"><i
                                    class="far fa-heart"></i></button>

                                {% endif %}

                            </form>
                            {% else %}

                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary"> {{ recipe.number_of_likes }}</span>
                        </strong>

                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>

                            <!-- Our total_comments variable goes before the closing strong tag -->

                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>

     <!-- Comment section -->

    <div class="row">
        <div class="col-md-8 card mb-4 mt-3">
            <h3>Comments:</h3>
            {% if comment_deleted %}
              <div class="alert alert-success" role="alert">
                  Your comment was deleted!
              </div>
            {% endif %}
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                        {{ comment.body | linebreaks }}

                        {% if user.is_authenticated and comment.email == user.email %}
                          <form class="d-inline" method="POST">
                              {% csrf_token %}

                              <div id="div_id_body" class="form-group">
                                <label for="id_body" class=" requiredField">Body<span class="asteriskField">*</span></label>
                                <div>
                                  <textarea name="body" cols="40" rows="10" class="textarea form-control" required="" id="id_body">
                                    {{ comment.body }}
                                  </textarea>
                                </div>
                              </div>

                              <input type="hidden" name="comment_id" value="{{ comment.id }}">
                              <input type="hidden" name="comment_task" value="edit">

                              <button type="submit" class="comment-submit btn btn-signup btn-lg">Edit Comment</button>
                          </form>

                          <form class="d-inline" method="POST">
                              {% csrf_token %}

                              <input type="hidden" name="comment_id" value="{{ comment.id }}">
                              <input type="hidden" name="comment_task" value="delete">

                              <button type="submit" class="comment-submit btn btn-signup btn-lg">Delete Comment</button>
                          </form>
                        {% endif %}

                </div>
                {% endfor %}
            </div>
        </div>

        <!-- User message -->

        <div class="col-md-4 card mb-4 mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    You comment is awaiting admin approval
                </div>
                {% else %}

                {% if user.is_authenticated %}

                <h2>Tell us what you think!</h2>
                <p>Posting as {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="comment-submit btn btn-signup btn-lg">Submit Comment</button>
                </form>
                {% endif %}
                {% endif %}

            </div>
        </div>
    </div>
</div>



{% endblock content %}